name: Remercier le contributeur et avertir le propriétaire

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main
      - develop

jobs:
  pr-thanks-and-alert:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Remercier le contributeur et avertir Helionux sur PR
        uses: actions/github-script@v7
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `Merci @${prAuthor} pour ta contribution ! 🚀\n\n@Helionux, un(e) nouveau(elle) contributeur(trice) a soumis une PR.`
            });

  push-alert:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Avertir Helionux à chaque commit sur main/develop
        uses: actions/github-script@v7
        with:
          script: |
            const commits = context.payload.commits;
            for (const commit of commits) {
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Notification: Nouveau commit de @${commit.author.username || commit.author.name}`,
                body: `@Helionux, un nouveau commit vient d'être poussé par @${commit.author.username || commit.author.name} ! \n\nMessage du commit : ${commit.message}\n\nLien du commit : ${commit.url}`
              });
            }
